### PR TITLE
feat: Support godot 4 projects

### PR DESCRIPTION
**Pull request by AntonioDell**
By using the github actions input `use_godot_4`, exports with godot 4 are now possible. There are some error outputs in the workflow log, but they do not seem to affect the resulting build.

You can check the builds in my repo:
- [Godot 4](https://github.com/AntonioDell/godot-export/actions/runs/3076412327) (I fixed the unexpected input warning after the build)
- [Godot 3](https://github.com/AntonioDell/godot-export/actions/runs/3076402624)

### CODE REVIEW

**Comment by firebelley** [comment]
@AntonioDell this looks excellent, the contribution is definitely appreciated!

I want to get this merged but have a question before I do. Currently there is an `editor_settings-3.tres` file in the `dist` directory that is used for basic editor settings required for exports. Is there a new `editor_settings` file for Godot 4? I haven't yet tried out Godot 4, so I'm sure it's possible that the format hasn't changed. But would be great to get confirmation from you that there's no a different settings file we'll need to support. The fact that your builds succeeded seems to indicate that it works just fine, but again just want to make sure!

**Comment by AntonioDell** [comment]
That is a good point, I didn't even notice the settings file. I need some time to check this :)

**Comment by AntonioDell** [comment]
The location of the editor settings remains the same as in godot 3, [as per documentation](https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html#editor-data-paths):
image

The format of the settings file is still the same, it may have some different keys (for a comprehensive list of options take a look at the [official docs](https://docs.godotengine.org/en/latest/classes/class_editorsettings.html), but the key used in `/dist/editor_setting-3.tres` still exists and did not change.

Does that answer your questions?

**Review by firebelley — APPROVED** [review]
Awesome, thanks for looking into that! All sounds good to me, I will get the merged and release the new version shortly!

**Pull request merged**
