### PR TITLE
Add Android configuration for runner.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
Hmm, so I've switched my action to use this fork, and am still getting complaints that jarsigner/adb/the Android SDK are unset. I was originally copying in my own file with these values, and upgrading to 2.5 broke that workflow since you're creating the file yourself now, so I'm pretty sure they're correct.

Any idea what I'm missing here? Seemed like a simple change, so I'm surprised it isn't working.

Thanks.

**Comment by firebelley** [comment]
That's interesting, if it was a just a 1:1 change I would have expected it to work. Can you post the error output?

Side note, I'll make a note to myself to make a PR that will ignore copying this file if it already exists. That way, if you want to use your own customized editor settings file then this action won't overwrite it.

**Comment by ndarilek** [comment]
2020-10-28T19:05:20.3666727Z ERROR: _fs_changed: Cannot export project 
with preset 'Android' due to configuration errors:
2020-10-28T19:05:20.3667608Z ADB executable not configured in the Editor 
Settings.
2020-10-28T19:05:20.3668097Z OpenJDK jarsigner not configured in the 
Editor Settings.

2020-10-28T19:05:20.3668602Z Custom build requires a valid Android SDK 
path in Editor Settings.


All three are included in the PR. Is there something I need to do to 
rebuild the action? I just used ndarilek/godot-export instead of your 
action, but that didn't do it.


Hoping to merge this soon, so happy to help out where I can in debugging 
this. I was having some issues exporting for Android under earlier 
versions of your action, and want to see if an upgrade resolves those.


Thanks.

**Comment by firebelley** [comment]
Here's what I can do, I'll merge this into master right now but I won't create a new release. You'll have to update your action to use `firebelley/godot-export@master`. If you wouldn't mind testing with that, that would be great. Once I have confirmation it worked or didn't work, we can move forward from there.

**Review by firebelley — APPROVED** [review]

**Comment by ndarilek** [comment]
Aww, sorry, rookie mistake. I didn't change the version after the @.


Anyhow, @master works. My APK exports now, and I no longer need a custom 
editor_settings. Might be a good idea to not overwrite it if it exists, 
but for me this is an improvement. Thanks for merging!

**Comment by firebelley** [comment]
Just released v2.6.0, so you can use that version instead of the master branch.

Thanks for contributing!

**Comment by ndarilek** [comment]
Works for me. Thanks for the new release!

**Pull request merged**
